Test multiple PHP versions

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,28 +3,60 @@
 # Check https://circleci.com/docs/2.0/language-php/ for more details
 #
 version: 2
-jobs:
-  build:
-    docker:
-      # specify the version you desire here
-      - image: php:7.2
-      
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/mysql:9.4
 
-    working_directory: ~/repo
-
-    steps:
+test: &test
+  steps:
       - checkout
 
       # Download and cache dependencies
       - restore_cache:
           keys:
-          - v1-dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
+          - v1-test-dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
           # fallback to using the latest cache if no exact match is found
-          - v1-dependencies-
+          - v1-test-dependencies-
+
+      # php:7.0 has no zip extension
+      - run: apt-get update -y && apt-get install unzip -y
+
+      - run: |
+          EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
+          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+          then
+              >&2 echo 'ERROR: Invalid installer signature'
+              rm composer-setup.php
+              exit 1
+          fi
+
+          php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+
+      - run: composer install -n --prefer-dist
+
+      - save_cache:
+          paths:
+            - ./vendor
+
+          key: v1-test--dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
+      # run tests!
+      - run: |
+          mkdir -p build/logs
+          vendor/bin/phpunit
+
+      - store_test_results:
+          path: build/logs
+
+test_and_cover: &test_and_cover
+  steps:
+      - checkout
+
+      # Download and cache dependencies
+      - restore_cache:
+          keys:
+          - v1-test-cover-dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
+          # fallback to using the latest cache if no exact match is found
+          - v1-test-cover-dependencies-
 
       - run: |
           EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
@@ -52,7 +84,7 @@ jobs:
             - /usr/local/lib/php/extensions/no-debug-non-zts-20170718
             - /usr/local/etc/php/conf.d/xdebug.ini
 
-          key: v1-dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
+          key: v1-test-cover-dependencies-{{ checksum "composer.json" }}--{{ checksum ".circleci/config.yml" }}
       - run:
           name: Setup Code Climate test-reporter
           command: |
@@ -73,3 +105,44 @@ jobs:
           vendor/bin/php-coveralls -o build.json -x build/logs/clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $? test-results/clover.xml
 
+jobs:
+  build:
+    docker:
+      # specify the version you desire here
+      - image: php:7.2
+
+      # Specify service dependencies here if necessary
+      # CircleCI maintains a library of pre-built images
+      # documented at https://circleci.com/docs/2.0/circleci-images/
+      # - image: circleci/mysql:9.4
+
+    working_directory: ~/repo
+
+    <<: *test_and_cover
+
+  build_php70:
+    docker:
+      - image: php:7.0
+
+    working_directory: ~/repo
+
+    <<: *test
+
+  build_php71:
+    docker:
+      - image: php:7.1
+
+    working_directory: ~/repo
+
+    <<: *test
+
+workflows:
+  version: 2
+
+  # Declare a workflow that runs all of our jobs in parallel.
+  test_cover_workflow:
+    jobs:
+      - build
+      - build_php70
+      - build_php71
+      - build_php72
